#generate_pheno_plink
#' merge phenotype measures with plink files and generate sex-seperated plink ped/map for each measure.
#'
#' @param ped.file ped file
#' @param map.file map file
#' @param pheno pheno dataframe generated by extract_pheno_ontol
#' @param outdir output folder for plink files
#' @param ncore Number of CPU cores to use, for parallel calculations.
#'
#' @return generate sex-seperated plink ped/map for each measure and a data.frame pheno.s. It contains the common strains with ped file
#'

generate_pheno_plink <- function(ped.file, map.file, pheno, outdir, ncore){
  #read map
  map <- read.table(map.file, header = FALSE, sep = "\t") %>%
    dplyr::mutate(V2 = case_when(
      V2 == "." ~ paste0(V1, "_", V4),
      TRUE ~ as.character(V2)
    ))
  ped <- fread(ped.file)
  ped <- ped %>%
    dplyr::mutate(V1 = gsub("?", "", V1, fixed = TRUE)) %>% #Note that the space in the strain name in the above plink will be replaced with ?. So remove "?"
    dplyr::mutate(V2 = gsub("?", "", V2, fixed = TRUE))
  #arrange by strain
  pheno.s <- pheno %>%
    dplyr::filter(sex %in% c("f", "m")) %>%
    dplyr::filter(strain %in% ped$V1) %>% #strain should be in ped
    dplyr::arrange(strain)
  #number of each strain
  pheno.n <- pheno.s %>%
    dplyr::group_by(strain) %>%
    dplyr::tally()
  #subset ped
  ped.s <- ped %>%
    dplyr::filter(V1 %in% pheno.s$strain) #strain should be in pheno
  all.equal(pheno.n$strain, ped.s$V1)
  #uncount by number of each strain
  pheno.ped.n <- tidyr::uncount(ped.s, weights = pheno.n$n)
  all.equal(pheno.ped.n$V1, pheno.s$strain)
  #combine pheno.s and  pheno.ped.n
  pheno.ped = bind_cols(pheno.s, pheno.ped.n) %>%
    dplyr::mutate(V5 = case_when( #sex
      sex == "f" ~ 2,
      sex == "m" ~ 1
    )) %>%
    dplyr::mutate(V6 = value)

  #for each measure
  parallel::mclapply(unique(pheno.ped$measnum), function(x){
    df = pheno.ped %>%
      dplyr::filter(measnum == x)
    #female--------
    if("f" %in% unique(df$sex)){
      df %>%
        dplyr::filter(sex == "f") %>%
        dplyr::select(V1:last_col()) %>%
        write.table(., file = paste0(outdir, x, ".f.ped"), #female
                    quote = FALSE, row.names = FALSE, col.names = FALSE, sep = " ")
      #map
      write.table(map, file = paste0(outdir, x, ".f.map"), #female
                  quote = FALSE, row.names = FALSE, col.names = FALSE, sep = " ")
      #pheno
      df %>%
        dplyr::filter(sex == "f") %>%
        dplyr::select(FID = V1, IID = V2, zscore) %>%
        write.table(., file = paste0(outdir, x, ".f.pheno"), #female
                    quote = FALSE, row.names = FALSE, col.names = FALSE, sep = " ")
    }
    #male--------
    if("m" %in% unique(df$sex)){
      df %>%
        dplyr::filter(sex == "m") %>%
        dplyr::select(V1:last_col()) %>%
        write.table(., file = paste0(outdir, x, ".m.ped"), #male
                    quote = FALSE, row.names = FALSE, col.names = FALSE, sep = " ")
      #map
      write.table(map, file = paste0(outdir, x, ".m.map"), #male
                  quote = FALSE, row.names = FALSE, col.names = FALSE, sep = " ")
      #pheno
      df %>%
        dplyr::filter(sex == "m") %>%
        dplyr::select(FID = V1, IID = V2, zscore) %>%
        write.table(., file = paste0(outdir, x, ".m.pheno"), #male
                    quote = FALSE, row.names = FALSE, col.names = FALSE, sep = " ")
    }
    gc()
  }, mc.cores = ncore)
  return(pheno.s)
}
