#rankz transform
rz.transform <- function(y){
  rankY=rank(y, ties.method="average", na.last="keep")
  rzT=qnorm(rankY/(length(na.exclude(rankY))+1))
  return(rzT)
}

#generate_ped_map
#' generate plink ped/map based on the genotype file
#'
#' @param genotype.file genotype file RDS file, for example: /projects/chesler-lab/phenome/metasoft/data/UCLA1_positions_with_MUSter_v2_genotypes.RDS. the first 5 column names are: "chr"       "bp38"      "marker"    "rs"        "observed"
#' @param ped.file ped file *.ped
#' @param map.file map file *.map. they should have the same name.
#'
#' @return ped.file and map file
#'
generate_ped_map <- function(genotype.file, ped.file, map.file){
  df = readRDS(genotype.file) %>%
    dplyr::filter(chr != "M") %>%
    dplyr::mutate(rs = if_else(rs == "", paste0(chr, "_", bp38), rs)) %>%
    dplyr::distinct(., chr, rs, bp38, .keep_all = TRUE)
  #map
  map = df %>%
    dplyr::select(chr, rs, bp38) %>%
    dplyr::mutate(cM = 0, .after = rs) %>%
    dplyr::mutate(rs = if_else(rs == "", paste0(chr, "_", bp38), rs)) %>%
    write.table(map.file, sep = "\t", quote = FALSE, row.names = FALSE, col.names = FALSE)
  #ped
  index <- which(names(df) == "observed")
  ped = df[, c(-1:-c(index))] %>%
    dplyr::rename(., "b_6" = "C57BL/6J") %>%
    dplyr::mutate(across(1:last_col(), ~ case_when(
      . == "N" ~ "0 0",
      . == "H" ~ "1 2",
      . == b_6 ~ "1 1",
      TRUE ~ "2 2"
    ))) %>%
    dplyr::rename(., "C57BL/6J" = "b_6") %>%
    t(.) %>%
    as.data.frame(.) %>%
    rownames_to_column(., var = "FID") %>%
    dplyr::mutate(IID = FID, .after = FID) %>%
    dplyr::mutate(PID = 0,   .after = IID) %>%
    dplyr::mutate(MID = 0,   .after = PID) %>%
    dplyr::mutate(SEX = 0,   .after = MID) %>%
    dplyr::mutate(PHE = -9,  .after = SEX) %>%
    write.table(ped.file, sep = "\t", quote = FALSE, row.names = FALSE, col.names = FALSE)
}

#extract_pheno_ontol
#' extract phenotype measures associated with ontology term
#'
#' @param url url of MPD. Default: "https://phenome.jax.org/"
#' @param ontology the name ontology term. for example "VT:0010488"
#'
#' @return one data.frame for all phenotype measures associated with ontology term
#'

extract_pheno_ontol <- function(url = "https://phenome.jax.org/",
                                ontology) {
  #if(missing(ontology))
  if (missing(ontology)) {
    stop(paste("The ontology cannot be missing. Please enter the ontology term!"))
  }
  #api
  api <- paste0(url, "api/pheno/measures_by_ontology/", ontology, "?csv=yes")
  #read
  message(paste0(" - Phenotype measures associated with ontology term ", ontology))
  #get phenotype measures associated with ontology term from api
  df = tryCatch(readr::read_csv(api, col_types = cols()),
                HTTPError = function(e) {
                  return(paste("HTTP error: ", trimws(e$message)))
                })

  #get the individual data for each measure in the df.
  dat <- map(df$measnum, safely(function(x){
    #get the data from api
    readr::read_csv(paste0(url, "api/pheno/animalvals/", x, "?csv=yes"), col_types = cols())
  })) %>%
    purrr::map(~.x$result) %>%
    setNames(df$measnum) %>%
    compact() #remove NULL from list
  #rbind
  dat_all <- do.call(rbind, dat) %>%
    dplyr::mutate(strain = gsub(" ", "", strain)) %>% #remove space from strain name
    mutate(strain = case_when(
      str_starts(strain, "CC")    ~ gsub('.{1}$', '', strain), #remove last character "J" from CC name
      TRUE                        ~ as.character(strain)
    ))
  return(dat_all)
}

#extract_pheno_measure
#' extract phenotype based on measure id
#'
#' @param url url of MPD. Default: "https://phenome.jax.org/"
#' @param measure_id measure ids
#'
#' @return one data.frame for all phenotype measures
#'

extract_pheno_measure <- function(url = "https://phenome.jax.org/",
                                  measure_id) {
  #get the individual data for each measure in the df.
  dat <- map(measure_id, safely(function(x){
    #get the data from api
    readr::read_csv(paste0(url, "api/pheno/animalvals/", x, "?csv=yes"), col_types = cols())
  })) %>%
    purrr::map(~.x$result) %>%
    setNames(measure_id) %>%
    compact() #remove NULL from list
  #rbind
  dat_all <- do.call(rbind, dat) %>%
    dplyr::mutate(strain = gsub(" ", "", strain)) %>% #remove space from strain name
    mutate(strain = case_when(
      str_starts(strain, "CC")    ~ gsub('.{1}$', '', strain), #remove last character "J" from CC name
      TRUE                        ~ as.character(strain)
    ))
  return(dat_all)
}

#generate_pheno_plink
#' merge phenotype measures with plink files and generate sex-seperated plink ped/map for each measure.
#'
#' @param ped.file ped file
#' @param map.file map file
#' @param pheno pheno dataframe generated by extract_pheno_ontol
#' @param outdir output folder for plink files
#' @param ncore Number of CPU cores to use, for parallel calculations.
#'
#' @return generate sex-seperated plink ped/map for each measure and a data.frame pheno.s. It contains the common strains with ped file
#'

generate_pheno_plink <- function(ped.file, map.file, pheno, outdir, ncore){
  #read map
  map <- read.table(map.file, header = FALSE, sep = "\t") %>%
    dplyr::mutate(V2 = case_when(
      V2 == "." ~ paste0(V1, "_", V4),
      TRUE ~ as.character(V2)
    ))
  ped <- fread(ped.file)
  ped <- ped %>%
    dplyr::mutate(V1 = gsub("?", "", V1, fixed = TRUE)) %>% #Note that the space in the strain name in the above plink will be replaced with ?. So remove "?"
    dplyr::mutate(V2 = gsub("?", "", V2, fixed = TRUE))
  #arrange by strain
  pheno.s <- pheno %>%
    dplyr::filter(sex %in% c("f", "m")) %>%
    dplyr::filter(strain %in% ped$V1) %>% #strain should be in ped
    dplyr::arrange(strain)
  #number of each strain
  pheno.n <- pheno.s %>%
    dplyr::group_by(strain) %>%
    dplyr::tally()
  #subset ped
  ped.s <- ped %>%
    dplyr::filter(V1 %in% pheno.s$strain) #strain should be in pheno
  all.equal(pheno.n$strain, ped.s$V1)
  #uncount by number of each strain
  pheno.ped.n <- tidyr::uncount(ped.s, weights = pheno.n$n)
  all.equal(pheno.ped.n$V1, pheno.s$strain)
  #combine pheno.s and  pheno.ped.n
  pheno.ped = bind_cols(pheno.s, pheno.ped.n) %>%
    dplyr::mutate(V5 = case_when( #sex
      sex == "f" ~ 2,
      sex == "m" ~ 1
    )) %>%
    dplyr::mutate(V6 = zscore) #use zscore as the phenotype column in ped file

  #for each measure
  parallel::mclapply(unique(pheno.ped$measnum), function(x){
    df = pheno.ped %>%
      dplyr::filter(measnum == x)
    #female--------
    if("f" %in% unique(df$sex)){
      df %>%
        dplyr::filter(sex == "f") %>%
        dplyr::select(V1:last_col()) %>%
        write.table(., file = paste0(outdir, x, ".f.ped"), #female
                    quote = FALSE, row.names = FALSE, col.names = FALSE, sep = " ")
      #map
      write.table(map, file = paste0(outdir, x, ".f.map"), #female
                  quote = FALSE, row.names = FALSE, col.names = FALSE, sep = " ")
      #pheno
      df %>%
        dplyr::filter(sex == "f") %>%
        dplyr::select(FID = V1, IID = V2, zscore, value) %>%
        write.table(., file = paste0(outdir, x, ".f.pheno"), #female
                    quote = FALSE, row.names = FALSE, col.names = FALSE, sep = " ")
    }
    #male--------
    if("m" %in% unique(df$sex)){
      df %>%
        dplyr::filter(sex == "m") %>%
        dplyr::select(V1:last_col()) %>%
        write.table(., file = paste0(outdir, x, ".m.ped"), #male
                    quote = FALSE, row.names = FALSE, col.names = FALSE, sep = " ")
      #map
      write.table(map, file = paste0(outdir, x, ".m.map"), #male
                  quote = FALSE, row.names = FALSE, col.names = FALSE, sep = " ")
      #pheno
      df %>%
        dplyr::filter(sex == "m") %>%
        dplyr::select(FID = V1, IID = V2, zscore, value) %>%
        write.table(., file = paste0(outdir, x, ".m.pheno"), #male
                    quote = FALSE, row.names = FALSE, col.names = FALSE, sep = " ")
    }
    gc()
  }, mc.cores = ncore)
  return(pheno.s)
}
